import { Router } from "express";

import {
  accountRouter,
  authRouter,
  bookingRouter,
  commentRouter,
  communityEventAttendanceRouter,
  communityEventOrderRouter,
  communityEventRouter,
  communityMemberRouter,
  communityPostRouter,
  communityReactionRouter,
  communityRouter,
  communityTwibbonRouter,
  courierRouter,
  deepLinkRouter,
  deviceRouter,
  eventAttendanceRouter,
  eventRouter,
  eventTicketTypeRouter,
  financeRouter,
  floorRouter,
  interestRouter,
  invitationRouter,
  invoiceRouter,
  ledgerRouter,
  locationRouter,
  logsRouter,
  mapsRouter,
  menuRouter,
  newsRouter,
  notificationRouter,
  operationalRouter,
  orderRouter,
  paymentRouter,
  pointsRouter,
  presenceRouter,
  profileRouter,
  promotionBannerRouter,
  promotionRouter,
  publicPlaceRouter,
  reviewPlaceRouter,
  reviewRouter,
  searchRouter,
  taskRouter,
  urlPreviewRouter,
  userBalanceRouter,
  usersRouter,
  venueBalanceRouter,
  venueCategoryRouter,
  venueRouter,
  venueServiceRouter,
  venueStaffRouter,
  venueSubCategoryRouter,
  venueUnitRouter,
  wellKnownRouter,
  withdrawRouter,
} from "modules";
import { createV1RouteRegistry, mountRoutes } from "./registry";
import { deprecatedRouters } from "./deprecated";

const router = Router();
const v1 = Router();

mountRoutes(
  v1,
  createV1RouteRegistry({
    auth: authRouter,
    booking: bookingRouter,
    invoice: invoiceRouter,
    maps: mapsRouter,
    presence: presenceRouter,
    users: usersRouter,
    device: deviceRouter,
    event: eventRouter,
    eventTicketType: eventTicketTypeRouter,
    floor: floorRouter,
    invitation: invitationRouter,
    location: locationRouter,
    logs: logsRouter,
    menu: menuRouter,
    news: newsRouter,
    notification: notificationRouter,
    operational: operationalRouter,
    order: orderRouter,
    payment: paymentRouter,
    points: pointsRouter,
    publicPlace: publicPlaceRouter,
    review: reviewRouter,
    reviewPlace: reviewPlaceRouter,
    userBalance: userBalanceRouter,
    venue: venueRouter,
    venueBalance: venueBalanceRouter,
    venueCategory: venueCategoryRouter,
    venueService: venueServiceRouter,
    venueSubCategory: venueSubCategoryRouter,
    venueUnit: venueUnitRouter,
    venueStaff: venueStaffRouter,
    withdraw: withdrawRouter,
    communities: communityRouter,
    communityMembers: communityMemberRouter,
    communityPosts: communityPostRouter,
    communityReactions: communityReactionRouter,
    communityEvents: communityEventRouter,
    communityTwibbons: communityTwibbonRouter,
    comments: commentRouter,
    urlPreview: urlPreviewRouter,
    ledger: ledgerRouter,
    communityAttendances: communityEventAttendanceRouter,
    attendances: eventAttendanceRouter,
    tasks: taskRouter,
    profiles: profileRouter,
    search: searchRouter,
    promotion: promotionRouter,
    courier: courierRouter,
    account: accountRouter,
    finance: financeRouter,
    deepLink: deepLinkRouter,
    wellKnown: wellKnownRouter,
    banners: promotionBannerRouter,
    interests: interestRouter,
    communityEventOrders: communityEventOrderRouter,
  }),
);

router.use("/api/v1", v1);
router.use(deprecatedRouters);

export default router;
